#!/bin/bash

# Only deal with branches that we have here *and* at the remote.
join <(git branch -r | cut -c 3- | sed "s/origin\///") <(git branch | cut -c 3-) |
while read -r line; do
  echo "========== BRANCH: ${line} =========="; git l ${line}..origin/${line} | cat;
done |
cat 
